from . import ml_demand_models
from . import inventory_prediction_model
from . import sale_order
from . import res_partner
from . import product
from . import product_trace
from . import stock_orderpoint
from . import stock_orderpoint_trace
from . import mrp_production
from . import mrp_production_trace
from . import stock_move
from . import stock_move_trace
from . import purchase_order
from . import purchase_order_trace
